import getUnicodeFlagIcon from "country-flag-icons/unicode";
import {
  SiReact,
  IconType,
  SiDocker,
  SiTypescript,
  SiRedux,
  SiGo,
  SiNextdotjs,
  SiJest,
  SiMongodb,
  SiPostgresql,
  SiNestjs,
  SiNodedotjs,
  SiAmazondynamodb,
  SiReactHex,
  SiTypescriptHex,
  SiGoHex,
  SiReduxHex,
  SiNextdotjsHex,
  SiJestHex,
  SiAmazondynamodbHex,
  SiMongodbHex,
  SiPostgresqlHex,
  SiNestjsHex,
  SiNodedotjsHex,
  SiDockerHex,
  SiTerraform,
  SiMysql,
  SiAwslambda,
  SiAmazonec2,
  SiAmazons3,
  SiGooglecloud,
  SiTerraformHex,
  SiMysqlHex,
  SiAwslambdaHex,
  SiAmazonec2Hex,
  SiAmazons3Hex,
  SiGooglecloudHex,
  SiGraphql,
  SiGraphqlHex,
  SiAdonisjs,
  SiAdonisjsHex,
  SiExpress,
  SiExpressHex,
  SiAmazonecs,
  SiAmazonecsHex,
  SiAmazonsqs,
  SiAmazonsqsHex,
  SiTailwindcss,
  SiTailwindcssHex,
  SiLinux,
  SiLinuxHex,
} from "@icons-pack/react-simple-icons";
import { FaLinkedin, FaGithub } from "react-icons/fa";
import { SiGmail } from "react-icons/si";

export const icons: Record<string, IconType> = {
  react: SiReact,
  typescript: SiTypescript,
  go: SiGo,
  redux: SiRedux,
  nextjs: SiNextdotjs,
  jest: SiJest,
  dynamodb: SiAmazondynamodb,
  mongodb: SiMongodb,
  postgresql: SiPostgresql,
  nestjs: SiNestjs,
  nodejs: SiNodedotjs,
  docker: SiDocker,
  terraform: SiTerraform,
  mysql: SiMysql,
  lambda: SiAwslambda,
  ec2: SiAmazonec2,
  s3: SiAmazons3,
  gcp: SiGooglecloud,
  graphql: SiGraphql,
  adonisjs: SiAdonisjs,
  express: SiExpress,
  ecs: SiAmazonecs,
  sqs: SiAmazonsqs,
  tailwind: SiTailwindcss,
  linux: SiLinux,
};

export const iconColors: Record<string, string> = {
  react: SiReactHex,
  typescript: SiTypescriptHex,
  go: SiGoHex,
  redux: SiReduxHex,
  nextjs: SiNextdotjsHex,
  jest: SiJestHex,
  dynamodb: SiAmazondynamodbHex,
  mongodb: SiMongodbHex,
  postgresql: SiPostgresqlHex,
  nestjs: SiNestjsHex,
  nodejs: SiNodedotjsHex,
  docker: SiDockerHex,
  terraform: SiTerraformHex,
  mysql: SiMysqlHex,
  lambda: SiAwslambdaHex,
  ec2: SiAmazonec2Hex,
  s3: SiAmazons3Hex,
  gcp: SiGooglecloudHex,
  graphql: SiGraphqlHex,
  adonisjs: SiAdonisjsHex,
  express: SiExpressHex,
  ecs: SiAmazonecsHex,
  sqs: SiAmazonsqsHex,
  tailwind: SiTailwindcssHex,
  linux: SiLinuxHex,
};

export const IconsSocialMedia = {
  IconLinkedIn: FaLinkedin,
  IconGithub: FaGithub,
  IconMail: SiGmail,
};

export const IconsFlags = {
  en_US: getUnicodeFlagIcon("US"),
  pt_BR: getUnicodeFlagIcon("BR"),
};
